image: Ubuntu2004

install:
  - wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
  - unzip packer_1.7.4_linux_amd64.zip



test_script:
  - ./packer --version
  - ./packer build server.pkr.hcl
  - ls -lh output-basic-example

build: off
