name: Build all

on:
  push:
    branches:
      - main

jobs:
  qemu:
    runs-on: [self-hosted, qemu]
    env: 
      PACKER_LOG: 1
      PACKER_CACHE_DIR: /home/github/github-actions/packer_cache/
      PKR_VAR_qemu_bridge: vmbr1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create directories
        run: mkdir -p logs screenshots
        
      - name: Prepare tools
        working-directory: ./tools/xva-img/
        run: |
          cmake .
          make
        
      - name: Build OPNSense Base
        env:
           PACKER_LOG_PATH: logs/opnsense-base.log
        run: |
           ./take_screenshots.sh logs/opnsense-base.log opnsense-base 60 &
           PID=$!
           packer build -only qemu.opnsense -var headless=true vms/opnsense/
           kill $PID

      - name: List opnsense-base artifacts
        run: ls -lh output/opnsense
        
     ############################################################################################
     #
     #                 VIRTUALBOX
     #
     ############################################################################################   
        
      - name: Convert to virtualbox
        if: ${{ github.ref == "refs/heads/main" || github.ref == "refs/heads/virtualbox" || startsWith(github.ref, "refs/tags/") }}
        env:
           PACKER_LOG_PATH: logs/opnsense-virtualbox.log
        run: packer build -only qemu.opnsense-virtualbox -var headless=true vms/opnsense/
        
        # TODO Test on virtualbox with virtualbox-ovf.opnsense-virtualbox-test

     ############################################################################################
     #
     #                 XCP-NG
     #
     ############################################################################################   

      - name: Convert to Xen
        if: ${{ github.ref == "refs/heads/main" || github.ref == "refs/heads/virtualbox" || startsWith(github.ref, "refs/tags/") }}
        env:
           PACKER_LOG_PATH: logs/opnsense-xen.log
        run: packer build -only qemu.opnsense-xen -var headless=true vms/opnsense/
              
      - name: Copy XCP-NG VM
        if: ${{ github.ref == "refs/heads/main" || github.ref == "refs/heads/virtualbox" || startsWith(github.ref, "refs/tags/") }}
        run: |
           mkdir -p output-xcp-ng
           cp /home/github/github-actions/hypervisors/xcp-ng.qcow2 output-xcp-ng/xcp-ng
           
      - name: Start XCP-NG VM
        if: ${{ github.ref == "refs/heads/main" || github.ref == "refs/heads/xen" || startsWith(github.ref, "refs/tags/") }}
        run: |
          qemu-system-x86_64 -machine type=pc,accel=kvm -cpu host -m 8192 -smp 8,sockets=2,cores=4  \
          -object iothread,id=io1 \
          -device virtio-blk-pci,drive=disk0,iothread=io1 \
          -drive if=none,id=disk0,cache=none,format=qcow2,aio=threads,file=output-xcp-ng/xcp-ng \
          -netdev user,id=user.0,net=192.168.122.0/24,dhcpstart=192.168.122.9,hostfwd=tcp::0-:22,hostfwd=tcp::0-:443 \
          -device virtio-net,netdev=user.0 \
          -netdev user,id=user.1,net=10.0.0.0/8,restrict=y \
          -device virtio-net,netdev=user.1 \
          -monitor unix:$PWD/mon.sock,server,nowait \
          -display none &
          
      - name: Get XCP-NG Ports
        if: ${{ github.ref == "refs/heads/main" || github.ref == "refs/heads/xen" || startsWith(github.ref, "refs/tags/") }}
        run: |
          ports=$(echo 'info usernet' | socat - UNIX-CONNECT:./mon.sock | grep HOST_FORWARD | tr -s ' ' | cut -d' ' -f 5,7)
          echo "== PORTS =="
          echo "$ports"
          while IFS= read -r line; do
              split=( $line )
              echo "Host: ${split[0]} Guest: ${split[1]}"
              echo "port_mapping_${split[1]}=${split[0]}" >> $GITHUB_ENV
          done <<< "$ports"
          
      - name: Wait for xcp-ng to boot
        if: ${{ github.ref == "refs/heads/main" || github.ref == "refs/heads/xen" || startsWith(github.ref, "refs/tags/") }}
        run: |
          until sshpass -p 'Muster!' ssh \
            -o UserKnownHostsFile=./known_hosts \
            -o "StrictHostKeyChecking no" \
            -p ${{ env.port_mapping_22 }} \
            root@localhost \
            "until xe vm-list; do sleep 10; done"
          do sleep 10; done
          
          # wait some more to make sure it is fully up
          sleep 30
          
        
      - name: Import VM
        if: ${{ github.ref == "refs/heads/main" || github.ref == "refs/heads/xen" || startsWith(github.ref, "refs/tags/") }}
        run: |
          sshpass -p 'Muster!' scp -P ${{ env.port_mapping_22 }} \
             -o "StrictHostKeyChecking no" \
             -o UserKnownHostsFile=./known_hosts \
             output/opnsense-xen/lmn7-opnsense.xva root@localhost:/opt/lmn7-opnsense.xva
             
          sshpass -p 'Muster!' ssh \
            -o UserKnownHostsFile=./known_hosts \
            -o "StrictHostKeyChecking no" \
            -p ${{ env.port_mapping_22 }} \
            root@localhost \
            "xe vm-import filename=/opt/lmn7-opnsense.xva"
         
      - name: Start VM
        if: ${{ github.ref == "refs/heads/main" || github.ref == "refs/heads/xen" || startsWith(github.ref, "refs/tags/") }}
        run: |
          sshpass -p 'Muster!' ssh \
            -o UserKnownHostsFile=./known_hosts \
            -o "StrictHostKeyChecking no" \
            -p ${{ env.port_mapping_22 }} \
            root@localhost \
            "xe vm-start vm=lmn7-opnsense"
        
      - name: Connect to opnsense on xen
        if: ${{ github.ref == "refs/heads/main" || github.ref == "refs/heads/xen" || startsWith(github.ref, "refs/tags/") }}
        run: |
          until sshpass -p 'Muster!' ssh \
            -o UserKnownHostsFile=./known_hosts \
            -o "StrictHostKeyChecking no" \
            -o ProxyCommand='sshpass -p "Muster!" ssh -o "StrictHostKeyChecking no" -p ${{ env.port_mapping_22 }} -W %h:%p root@localhost' \
            root@10.0.0.254 \
            "hostname"
          do sleep 5; done
            
          echo "Test wan connectivity"
          sshpass -p 'Muster!' ssh \
            -o UserKnownHostsFile=./known_hosts \
            -o "StrictHostKeyChecking no" \
            -o ProxyCommand='sshpass -p "Muster!" ssh -o "StrictHostKeyChecking no" -p ${{ env.port_mapping_22 }} -W %h:%p root@localhost' \
            root@10.0.0.254 \
            "curl http://example.org"

      - name: List output
        run: |
          ls -l output-*
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs
          path: logs/
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: screenshots/
