name: QEMU Test
concurrency: vm_host

on:
  push:

jobs:
  qemu:
    runs-on: [self-hosted, qemu]
    steps:
      - uses: actions/checkout@v2
      - name: Build XCP-NG VM
        run:
           PACKER_LOG=1 packer build -var headless=true build_infrastructure/xcp-ng.pkr.hcl
