name: XCP-NG
concurrency: vm_host

on:
  push:

jobs:
  qemu:
    runs-on: [self-hosted, qemu]
    env: 
      PACKER_LOG: 1
      PACKER_CACHE_DIR: /home/github/actions-runner/packer_cache/
    steps:
      - uses: actions/checkout@v2
      - name: Create directories
        run: mkdir -p logs screenshots
      - name: Build XCP-NG VM
        env:
           PACKER_LOG_PATH: logs/xcp-ng.log
        run: |
           ./take_screenshots.sh logs/xcp-ng.log xen 60 &
           PID=$!
           packer build -only qemu.xcp-ng -var headless=true build_infrastructure
           kill $PID
      - name: Convert to non sparse raw
        run: qemu-img convert -S 0 output-xcp-ng/xcp-ng output-xcp-ng/xcp-ng.raw
        
      - name: Start XCP-NG VM
        run: |
          qemu-system-x86_64 -machine type=pc,accel=kvm -cpu host -m 8192 -smp 8,sockets=2,cores=4  \
          -object iothread,id=io1 \
          -device virtio-blk-pci,drive=disk0,iothread=io1 \
          -drive if=none,id=disk0,cache=none,format=raw,aio=threads,file=output-xcp-ng/xcp-ng.raw \
          -netdev user,id=user.0,net=192.168.122.0/24,dhcpstart=192.168.122.9,hostfwd=tcp::0-:22,hostfwd=tcp::0-:443 \
          -device virtio-net,netdev=user.0 \
          -netdev user,id=user.1,net=10.0.0.0/8,restrict=y \
          -device virtio-net,netdev=user.1 \
          -monitor unix:$PWD/mon.sock,server,nowait &
      - name: Get XCP-NG Ports
        run: |
          ports=$(echo 'info usernet' | socat - UNIX-CONNECT:./mon.sock | grep HOST_FORWARD | tr -s ' ' | cut -d' ' -f 5,7)
          while IFS= read -r line; do
              split=( $line )
              echo "Host: ${split[0]} Guest: ${split[1]}"
              echo "port_mapping_${split[1]}=${split[0]}" >> $GITHUB_ENV
          done <<< "$ports"
      - name: Wait for xcp-ng to boot
        run: sleep 300
      - name: Install packer plugins
        run: packer init 18
        
      - name: Build OPNSense
        env:
           PACKER_LOG_PATH: logs/opnsense.log
        run: |
          ./take_screenshots.sh logs/opnsense.log opnsense 10 &
          PID=$!
          packer build -only xenserver-iso.opnsense \
          -var xcp_keep=always \
          -var xen_api_port=${{ env.port_mapping_443 }} \
          -var xen_ssh_port=${{ env.port_mapping_22 }} \
          18
          
          kill $PID
      - name: Start OPNSense
        run: |
          sshpass -p 'Muster!' ssh \
            -o "StrictHostKeyChecking no" \
            -p 42371 \
            root@localhost \
            "UUID=$(xe template-list name-label=opnsense --minimal) \
            && xe template-param-set uuid=$UUID is-a-template=false \
            && xe vm-list \
            && xe vm-start uuid=$UUID && xe vm-list"
          
      - name: Build Server
        env:
           PACKER_LOG_PATH: logs/server.log
        run: |
          ./take_screenshots.sh logs/server.log server 60 &
          PID=$!
          packer build -only xenserver-iso.server \
          -var xcp_keep=always \
          -var xen_api_port=${{ env.port_mapping_443 }} \
          -var xen_ssh_port=${{ env.port_mapping_22 }} \
          18
          
          kill $PID
          
      - name: List output
        run: |
          ls -l output-*
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs
          path: logs/
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: screenshots/
